# Generated by Django 2.2 on 2019-04-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watcher', '0002_auto_20190416_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='seatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True)),
                ('seatImage', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
